/*Função para calcular idade a partir da data de nascimento:*/
CREATE OR REPLACE FUNCTION CALC_IDADE(
V_DATA IN DATE)
RETURN NUMBER IS
VV_DATA NUMBER;
BEGIN
SELECT TRUNC((MONTHS_BETWEEN(SYSDATE, TO_DATE(V_DATA,'DD/MM/RR')))/12) AS IDADE INTO VV_DATA FROM DUAL;
RETURN VV_DATA;
END CALC_IDADE;
/

/*Verificando a idade de uma pessoa:*/
SELECT CALC_IDADE(DATA_NASCIMENTO) FROM DADOS WHERE COD_CADASTRO = 2;
